### ISSUE TITLE
Invalid state

### ISSUE THREAD

**Issue by margyly** [auth0/auth0-drupal#107]
I'm using the module from GitHub and I am getting "invalid state" errors in Drupal 8:

Location: http://uua_d8.dd:8083/auth0/callback?code=m1oeWYyO7WBWYmK1&state=DTW6pOH...
Message: Failed to exchange code for tokens: Invalid state

Requiring "auth0/auth0-php": "5.0.6" in composer.json does not solve the problem.

Any ideas or help will be appreciated.

**Comment by joshcanhelp** [comment]
@margyly - The Auth0 PHP version you want is in the `composer.json` file here:

https://github.com/auth0/auth0-drupal/blob/master/composer.json#L7

5.1 or greater should fix that `state` error message (security enhancement added in that version). 

Sorry for the trouble here ... give that a try and let me know if you're still having issues.
