### ISSUE TITLE
What happens if exception happens in Drupal?

### ISSUE THREAD

**Issue by duartegarin** [auth0/auth0-drupal#118]
Hi,
I'm evaluating auth0 for our platform that has a Drupal CMS backend exposing content via GraphQL to multiple React applications.

From what I can understand, it would be possible to handle the login/signup workflow in react and leverage this module to create the users in Drupal and having them in synch with auth0.

What I'm trying to understand is, what happens if the process fails in Drupal? Would we end up with user successfully registered in auth0 but without a user account? Is there any exception handling that prevents a successful account creation if the Drupal account creation fails, to prevent "orphan" accounts?

Thanks in advance!
Duarte

**Comment by duartegarin** [comment]
Hi @joshcanhelp ,
Thank you so much for the quick reply!

Ideally I don't want to expose our cms backend to users so I might need to consider another approach.
I suppose you're right, maybe orphaned accounts aren't a huge deal.

Maybe I could use auth0 react lib, handle the entire process in react and when the first GraphQL request needs to be send to Drupal, I can check for the drupal uid in the auth0 metadata. If present I already have a user in Drupal, if not I can create the user via GraphQL.

That way I would probably not need the Drupal auth0 module. Do you see any flaws with this approach?

Thank you again for your help!

**Comment by joshcanhelp** [comment]
As long as you follow what the callback is doing in terms of security recommendations (state checking and ID token validation being the main ones), that should work fine. Typically orphaned accounts happen en masse when something goes wrong (during setup, errant configuration changes, etc). Just make sure you're tracking them in case something larger is amiss.

**Comment by duartegarin** [comment]
Awesome, will give this approach a try.
Thanks again for the help @joshcanhelp !
