### ISSUE TITLE
Configuring Auth0 URL parameters

### ISSUE THREAD

**Issue by nodomain** [auth0/auth0-drupal#119]
This one is similar to https://github.com/auth0/wp-auth0/issues/521

For our setup we need to be able to add parameters to the Authorize URL.
The desired URL would be ```https://sub-tenant.eu.auth0.com/authorize?connection=main-tenant-oidc&display=sub```

Thanks for accepting this enhancement issue :-)

**Comment by joshcanhelp** [comment]
Thanks for the report @nodomain! We're accepting Pull Requests if you want to take a crack at it. Otherwise, I'll leave this open so it can be picked up later 👍
