### ISSUE TITLE
Resend verification link leads to blank page

### ISSUE THREAD

**Issue by IgsuMustonen** [auth0/auth0-drupal#126]
### Description

When a user clicks on the resend email verification link, the href value leads to a blank page.

### Environment

* Module version: 2.1
* Drupal version:  8.6.4
* Browser version:  Firefox

### Reproduction

Make sure email verification is required. Create new user and before verifying email, attempt to log in. This should show a red error message about email not verified, click on the resend vericiation email and then the browser shows a blank page (as it tries to browse to javascript:null, which doesn't exist)

### Proposed solution

The href property is located at /src/Controller/AuthController.php line 703. This could be changed from `href="javascript:null"` to simply `href="#"`.

I tested the above mentioned solution in both environments and it works, the page reloads itself and then a green message box confirms that the verification email was resent.

**Comment by IgsuMustonen** [comment]
Thanks for the quick answer!

I've got some more detailed information regarding this issue. It seems to be happening only in Firefox (Tested on Windows 10 on the latest version). The console is not giving any errors.

Apparently my client is also having this isssue using Firefox. Could you please confirm?

**Comment by joshcanhelp** [comment]
@IgsuMustonen - I just tried with Firefox and see that issue now as well. It looks like changing that to `javascript:;` instead works in the same way. I'll put through a PR to fix that ASAP. If you want to try that on your end as well, it would be helpful. 

Thank you for the report!
