### ISSUE TITLE
drupal jwt 

### ISSUE THREAD

**Issue by shaksi** [auth0/auth0-drupal#128]
i currently a react native app that logins in directly using json web token  and then do bunch of calls via api.

i would like to remove the current authentication process and replace with auth0, is it possible to login directly to drupal with the accessToken provided by auth0?

**Comment by joshcanhelp** [comment]
@shaksi - Apologies for the late reply here. 

I don't think I'm totally clear on your question here. If this is still something you're working on, can you give me a little more information about what you're looking to do? Is this a React Native app that is using a Drupal-provided API? In that case you'll want to use [the SPA flow](https://auth0.com/docs/flows/guides/single-page-login-flow/call-api-using-single-page-login-flow) in your React Native app and then [protect the API like the example here](https://auth0.com/docs/quickstart/backend/php). That second quickstart uses the PHP SDK, which is included in the Drupal module but also can be used separately. If you're just providing an API in Drupal, the module is not necessary.
