### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by edysmp** [auth0/auth0-drupal#130]
### Description

I am testing this with drupal 7 and I am getting this error after a login.
Error
The website encountered an unexpected error. Please try again later.
```GuzzleHttp\Exception\ClientException: Client error: `GET https://myaccount.auth0.com/api/v2/users/auth0%7C5c79b1854db6391d5dce9858` resulted in a `401 Unauthorized` response: {"statusCode":401,"error":"Unauthorized","message":"Invalid token","attributes":{"error":"Invalid token"}} in GuzzleHttp\Exception\RequestException::create() (line 111 of /var/www/html/sites/all/modules/contrib/auth0-drupal-d7-2.x.x/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php).```

I am using version `d7-2.x.x` of this module.
Is there support for drupal 7?

Checking Logs in my dasboard I see these events:

- Success Exchange
- Success Login
- Failed Silent Auth

**Comment by joshcanhelp** [comment]
@edysmp - Thanks for the report here. There is minimal support for Drupal 7 at the moment, though there are a couple of PRs open now that might improve the experience there. Right now, the focus is Drupal 8.

That said, it looks like you're trying to call the Management API for user information. I'm not seeing that in either version of the module. Can you tell me what version you're using? And confirm that this isn't in a custom module of any kind?

**Comment by edysmp** [comment]
@joshcanhelp I am using d7-2.x.x branch for a drupal7 project(We have projects in d7 and d8 that we want to use SSO on them). I've applied this PR https://github.com/auth0/auth0-drupal/pull/120 and it seems work good.

**Comment by joshcanhelp** [comment]
OK, great, thank you for the feedback on that. I'll try to help move that along.
