### ISSUE TITLE
Issue with returnTo/state post callback

### ISSUE THREAD

**Issue by SumanaMalkapuram** [auth0/auth0-drupal#136]
Having an issue with the returnTo parameter.

Here is the issue:

Start login at /node/99 -> which takes me to /user/login if there is no session -> authenticates the user against Auth0 after building the authorize URL -> callback to module -> Here it returns to /user page instead of /node/99 where i started the authentication.
I see the https://github.com/auth0/auth0-drupal/blob/master/src/Controller/AuthController.php is accepting returnTo URL, but is not redirecting back to that URL after authentication is complete and callback service is call.

**Comment by joshcanhelp** [comment]
Thank you @SumanaMalkapuram! I'll make sure to take a look at this and get it in the upcoming release.
