### ISSUE TITLE
Failed to exchange code for tokens: Invalid state

### ISSUE THREAD

**Issue by bkildow** [auth0/auth0-drupal#139]
### Description

After configuring this module, I've hit the following error: `Failed to exchange code for tokens: Invalid state`. I'm using the universal login page. After much debugging, I have figured out that the root cause of this is session cookies aren't being set for the anonymous user in drupal. D8 uses lazy sessions, so even though there is a session id present, it won't persist unless the full session is started, and the session cookie is set. I believe this can be fixed by using this approach: https://drupal.stackexchange.com/a/163415/398, instead of using `SessionManager` here: https://github.com/auth0/auth0-drupal/blob/aead0f9fd3ef9c3cf5265274b8a7864b911c89f3/src/Controller/AuthController.php#L322. I'll see if I can get a PR up for this.

### Environment

Please provide the following:

* Module version: 2.1
* Drupal version: 8.7-alpha1
* PHP version: 7.2

**Comment by joshcanhelp** [comment]
See PR for discussion.
