### ISSUE TITLE
"Please verify your email" message is shown as HTML code

### ISSUE THREAD

**Issue by thirdender** [auth0/auth0-drupal#145]
### Description

When a user who's e-mail has not been verified attempts to log in, the following message is displayed.

![Screenshot from 2019-06-18 11-00-52](https://user-images.githubusercontent.com/457620/59695628-88676c00-91b8-11e9-84a9-3cfd55240863.png)

This can be fixed by passing a rendered message to `drupal_set_message`:

```
drupal_set_message(\Drupal\Core\Render\Markup::create('<strong>Your HTML here</strong>'));
```

If a string is passed, it is automatically sanitized.

### Environment

Please provide the following:

* Module version: 8.x-2.2
* Drupal version: 8.7.3
* PHP version: 7.3.6

**Comment by joshcanhelp** [comment]
@thirdender - Apologies for the trouble here. I can confirm that on my end as well, that should not have slipped through. I'll assign this to myself and get a patch out ASAP. 

Thank you for the report!
