### ISSUE TITLE
Drupal Profile and Auth0 metadata sync

### ISSUE THREAD

**Issue by AmyyP** [auth0/auth0-drupal#146]
hello,
i installed auth0-drupal (Drupal8.7 + https://www.drupal.org/project/auth0 ) module. which is working fine with new signup and login. but its not updating drupal profile fields with Auth0 user meta data(i.e. firstname, lastname) which are defined in drupal-auth0- advance settings tab(admin/config/auth0/advanced -> Mapping of Claims to Profile Fields (one per line) and Lock extra settings). Firstname, Lastname stored correctly as user_metadata on Auth0 but not in Drupal profile. Also i checked for any updated file for drupal-auth0 module and all files looks with new updates/fixes.(i.e. Authcontroller.php, auth0.lock.js)
what setting should i do to sync these metadata and drupal profile fields??

Thank you in advance!! :)

**Comment by joshcanhelp** [comment]
Hi @AmyyP ... the claims that this setting refers to are [root-level profile attributes](https://auth0.com/docs/api/management/guides/users/update-root-attributes-users), which do not include `user_metadata` or `app_metadata`. The typical format is this:

```
{
    "sub": "auth0|1234567890",
    "nickname": "josh.cunningham",
    "name": "josh",
    "picture": "https://s.gravatar.com/avatar/ae098a33ae2acd0fd647f48749f8630c?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fjo.png",
    "updated_at": "2019-06-26T23:16:18.484Z",
    "email": "xyz@auth0.com",
    "email_verified": true
}
```

You can add [custom claims](https://auth0.com/docs/scopes/current/custom-claims) if you need anything beyond what's sent back by default (which can pull from metadata).

Hope that helps!
