### ISSUE TITLE
implementing auth0 with decoupled drupal

### ISSUE THREAD

**Issue by mmmaxxx** [auth0/auth0-drupal#150]
i'm looking to implement auth0 in a decoupled drupal project with angular frontend, should i be using this drupal module or proceeding as answered in #128 and implementing the SPA flow in the angular app ? thanks

**Comment by joshcanhelp** [comment]
@mmmaxxx - Totally depends. If you need to log in to Drupal and can use cookies to authenticate against a Drupal-served API, then this module is fine. If you're building a SPA talking to an API on a different domain and don't need Drupal authentication, then you'll need to use [our SPA JS SDK](https://github.com/auth0/auth0-spa-js). Just depends on how your application is architected.

Let me know if you have any other questions!
