### ISSUE TITLE
Change Drupal user roles based on Auth user roles

### ISSUE THREAD

**Issue by ozeberle** [auth0/auth0-drupal#152]
I want to change roles for some users and assign them as administrators.
I mean, when a specific user logs in Drupal, his role is set automatically to administrator based on the Auth role previously assigned.
I completed **Claim for role mapping** in Auth0 advanced configuration at Drupal configuration with "roles" (without quotes) and "admin|administrator" in **Mapping of Claim Role Values to Drupal Roles** field.
Also, I activated **Authorization** extension module inside of Auth0, created a role admin and assigned this role to a few users.
Then I went to **Rules** menu (out of Authorization extension module) and created the same rule as is described here: https://github.com/auth0/auth0-drupal/issues/123 but in my case I tried different Urls. 
What namespace should I use there? Because I tried many Urls with any good results. Drupal tell me: 'no changes to role detected'.

Also I tried adding "roles" to app_metadata but nothing changed.

I read what @joshcanhelp posted in the link above but honestly, I didn't understand.
I hope you can help me soon.

### Environment

Please provide the following:

* Module version: 8.x-2.3
* Drupal version: 8.6
* PHP version: 7.2
* Additional modules: Authorization extension module.

**Comment by joshcanhelp** [comment]
@ozeberle - Apologies for the trouble here. We have a whole document on namespacing here:

https://auth0.com/docs/tokens/concepts/claims-namespacing

Just make sure what you have in the Drupal admin for the claim matches what you're using in the Rule exactly. 

Roles in the example in the PR you linked to are using `user_metadata`, not `app_metadata`. Those are 2 different fields. 

Also ... if you're seeing the "no changes to role detected," are you sure the one for the user is different than the one already saved in Drupal? No change might mean the roles are the same.
