### ISSUE TITLE
Module does not appear in the drupal configuration page (Drupal 8)

### ISSUE THREAD

**Issue by rmiroballi** [auth0/auth0-drupal#30]
I've installed the module using the instructions provided, except into the modules directory for drupal 8 (which seems to be /var/www/html/modules/)

The module configuration does not appear in the modules configuration. I've installed other modules and they do appear. There are no errors in the logs

drupal 8 (latest) I am using a vanilla installation on mySQL
auth0 /drupal8 branch

**Comment by glena** [comment]
hi @rmiroballi 

did you use the code under this branch https://github.com/auth0/auth0-drupal/tree/drupal8?

The code on master is not compatible with drupal 7 since drupal changed the entire API.

**Comment by rmiroballi** [comment]
Yes, I'm using the drupal8 branch.

**Comment by glena** [comment]
and does the module appears on the list of modules to install it? (under `/admin/modules`)

**Comment by rmiroballi** [comment]
No, that's the issue.

**Comment by glena** [comment]
and did you upload the module dependencies?

You can either download them on your local environment using `composer install` and uploading the vendor folder or following one of the recomendations after `composer manager` being deprecated https://www.drupal.org/node/2405811 (check under `Notice: As of Drupal 8.1,`).

**Comment by rmiroballi** [comment]
Yes, I did the local copy to server. The deps are in the vendor folder.  I can blow that away and try one of the methods in the article.

**Comment by glena** [comment]
Upload the vendor folder should work... I asked Taylor to set up a call with you guys to troubleshoot

**Comment by rmiroballi** [comment]
Resolved

**Comment by glena** [comment]
nice to hear :)
