### ISSUE TITLE
demo app not working

### ISSUE THREAD

**Issue by thedavidmeister** [auth0/auth0-drupal#33]
I'm getting a 403 on the demo app:

<img width="986" alt="screen shot 2016-09-28 at 4 02 34 pm" src="https://cloud.githubusercontent.com/assets/629710/18902232/fc847fde-8594-11e6-8a8a-c5be739884f7.png">

**Comment by anakinjay** [comment]
same here

**Comment by joshcanhelp** [comment]
Removed in #87
