### ISSUE TITLE
Register with packagist.org

### ISSUE THREAD

**Issue by josephdpurcell** [auth0/auth0-drupal#35]
Would a auth0 maintainer mind submitting this to https://packagist.org/packages/submit ?

While this module is going through the review process on drupal.org, having it on packagist.org would at least allow the installer of this module to not have to add a custom repository like this:

```
    "repositories": {
        "auth0": {
            "url": "https://github.com/auth0/auth0-drupal.git",
            "type": "git"
        }
    }
```

**Comment by josephdpurcell** [comment]
Before registering it, there is a problem with the name. Will post back soon.

**Comment by josephdpurcell** [comment]
Ok, I've described the problem with the current package name here: https://github.com/auth0/auth0-drupal/issues/36

Before registering with packagist, it might be helpful to correct the naming.

**Comment by josephdpurcell** [comment]
I closed the other ticket so I'll describe the naming problem here: when you install the module using a composer workflow it installs it at `modules/contrib/$name`, which means the module will get installed as `modules/contrib/drupal`, which is not the project name.

Suggested resolution: rename the package to `drupal/auth0`.

**Comment by josephdpurcell** [comment]
PR #39 will need merged before registering with packagist.org.

**Comment by glena** [comment]
checking...

**Comment by glena** [comment]
what I thought, you can't set the vendor name to `drupal` and publish it in packagist. what about `auth0/auth0-drupal`?

**Comment by glena** [comment]
@josephdpurcell ☝️

**Comment by josephdpurcell** [comment]
@glena Fascinating. Perhaps these are just grandfathered in?

* https://packagist.org/packages/drupal/payment
* https://packagist.org/packages/drupal/tqextension

That is unfortunate, considering once it is adopted on to drupal.org it has to be `drupal/auth0`.

The name `auth0/auth0-drupal` won't work because hyphens aren't allowed in module names. It would get installed as `modules/contrib/auth0-drupal`. Naming it `auth0/auth0_drupal` would get around this, however, we also have the problem of namespacing: can Drupal load a class that has a namespace different than its module name. Can Drupal load a class `Drupal\auth0\Controller\AuthController` that is inside `modules/contrib/auth0_drupal`?

I'll see if I can do some investigation.

**Comment by josephdpurcell** [comment]
It looks like it works! Today I learned that Drupal will in fact load `Drupal\auth0\Controller\AuthController` even if its inside `modules/contrib/auth0_drupal`. I'll submit a PR.

**Comment by josephdpurcell** [comment]
The following now works with composer:

```
    "repositories": {
        "auth0": {
            "type": "git",
            "url": "https://github.com/josephdpurcell/auth0-drupal.git"
        }
```

and requiring it:

```
composer require auth0/auth0_drupal:dev-drupal8 
```

**Comment by glena** [comment]
cool, I will check this tomorrow then

**Comment by glena** [comment]
Ok ready https://packagist.org/packages/auth0/auth0_drupal

Thx for your contributions

**Comment by josephdpurcell** [comment]
@glena It works! Thank you so much for being open to these changes!

Now, for any Drupal 8 project that is using composer, all they will need to do is:

```
composer require auth0/auth0_drupal
```

No need to add a custom repository or anything like that, and all the additional dependencies that auth0_drupal needs will be automatically downloaded as well, because composer. (i.e. they won't need to `cd modules/contrib/auth0_drupal` and run composer install there)

This is great news!

**Comment by glena** [comment]
@josephdpurcell One thing (you probably already realise that). For drupal 7 you should use v1 and for drupal 8 you should use v2

**Comment by josephdpurcell** [comment]
Confession: I didn't know what the versions were signifying. The pattern Drupal uses is similar to `7.x-1.x` or `8.x-1.x`, for example: https://github.com/timmillwood/drupal-workspace/releases. Here are two related docs:

* https://www.drupal.org/docs/7/choosing-drupal-version/version-numbers
* https://www.drupal.org/docs/7/choosing-a-drupal-version/release-types

I think the v1 and v2 tags are fine, but they may warrant a description either in the README or the tag's annotation.

One benefit of switching to the 8.x-1.x model is it will make it easier to sync to drupal.org and back.

**Comment by josephdpurcell** [comment]
Given the above, the composer command for Drupal 8 should be:

```
composer require auth0/auth0_drupal:2.0.*
```

**Comment by glena** [comment]
hi @josephdpurcell do you have any idea on why it could be failing? See the issue #53. Thank you beforehand :)

**Comment by glena** [comment]
@josephdpurcell really appreciated you input on the other issue. Shoot me an email to german [at] auth0 [.] com.
