### ISSUE TITLE
Align with typical patterns for managing composer dependencies

### ISSUE THREAD

**Issue by josephdpurcell** [auth0/auth0-drupal#41]
# Background

Typically, what I've seen in Drupal 8 contrib space is to allow the user to manage their dependencies using composer in one of two ways:

1. The Drupal's composer.json
1. The Composer Manager module

For reference, see [Using Composer in a Drupal project](https://www.drupal.org/docs/develop/using-composer/using-composer-in-a-drupal-project) and [Installing modules' Composer dependencies](https://www.drupal.org/docs/8/extending-drupal/installing-modules-composer-dependencies).

Here are examples of two projects that do this:

* See "Installation" section https://www.drupal.org/project/relaxed
* See "Existing Site" section http://docs.drupalcommerce.org/v2/install.html

# Problem

The problem with the `drupal8` branch is that you cannot manage the module's dependencies in this way due to the autoloader require statement. This forces the site builder to manually run `composer install` within the module directory.

# Proposed Resolution

Remove the autoloader require statement. This will allow site builders to follow Drupal conventions for managing composer dependencies.

**Comment by glena** [comment]
👍 merged

**Comment by glena** [comment]
Thx for the contribution

**Comment by josephdpurcell** [comment]
Side note: here is a gist for applying to a D8 module that was installed that includes the vendor include statement: https://gist.github.com/josephdpurcell/6e51b23fe4ed2608b0bd50d87df22195.

If you're using cweagans/composer-patches you can do:

```
        "patches": {
            "auth0/auth0_drupal": {
                "Remove the autoloader statement to comply with PSR4 autoloader, see Auth0 issue 41": "https://gist.githubusercontent.com/josephdpurcell/6e51b23fe4ed2608b0bd50d87df22195/raw/                     25a6a780d1040db46de561140ba3c3a1c79a9529/auth0-drupal-module-patch-remove-autoloder-for-composer.patch"
            }
        }
```

To apply the patch. If you're using the latest "drupal8" branch this patch is not needed.
