### ISSUE TITLE
Support Drupal Code Style

### ISSUE THREAD

**Issue by josephdpurcell** [auth0/auth0-drupal#46]
Currently, the `drupal8` branch does not follow the Drupal code style very well. This will be important during the Drupal project review [drupal.org/node/2298559](https://www.drupal.org/node/2298559). Details on the Code Style can be found here: [https://www.drupal.org/docs/develop/standards](https://www.drupal.org/docs/develop/standards).

# Proposed Resolution

Configure Code Climate to show checks for Drupal code style (currently it does not, [link](https://codeclimate.com/github/auth0/auth0-drupal)) and configure GitHub to integrate with Code Climate. This will give a per-pull-request view of whether code style adherence is improving or degrading. Likely, this is preferable to updating all the code at once.

**Comment by glena** [comment]
nice

**Comment by josephdpurcell** [comment]
:+1: Results are now displaying on Code Climate https://codeclimate.com/github/auth0/auth0-drupal/issues

If I get some time I'll submit a PR to help improve the code style compliance.
