### ISSUE TITLE
Error: Class 'Auth0SDK\Auth0' not found in Drupal\auth0\Controller\AuthController->callback() (line 71 of /var/www/webapp/web/modules/contrib/auth0/src/Controller/AuthController.php).

### ISSUE THREAD

**Issue by nlighteneddesign** [auth0/auth0-drupal#53]
I used composer to install the SDK and it's in web/vendor/auth0. Is there something I'm doing wrong? The controller isn't recognizing the SDK.

**Comment by glena** [comment]
is this drupal 7 or 8?

**Comment by nlighteneddesign** [comment]
Sorry, drupal 8. I'm on your master branch should I be on the 8.x tag?

**Comment by glena** [comment]
How did you installed?

If you run `compose require auth0/auth0_drupal:^2.0.0` in the root of your site it should do the trick (it shoudl download all the dependencies along with the module).

**Comment by nlighteneddesign** [comment]
Ah no, I downloaded this and installed it normally, then ran `composer require auth0/auth0-php` to include the sdk which is where I thought the dependencies were.

Running `composer require auth0/auth0_drupal:^2.0.0` worked better but now I get this error:
	

> Error: Class 'OAuth2\Client' not found in Auth0SDK\Auth0->__construct() (line 206 of /var/www/webapp/web/vendor/auth0/auth0-php/src/Auth0.php).

**Comment by glena** [comment]
That could be related to the minimun stability configured in composer. Try adding this two entries in the composer.json file (under `require`, like [here](https://github.com/auth0/auth0-drupal/blob/master/composer.json#L8-L9))

```
"adoy/oauth2": "dev-master",
"firebase/php-jwt" : "dev-master"
```

and run `composer update`

**Comment by nlighteneddesign** [comment]
After doing that I get the same error
composer.json looks like this:
        
       

> "auth0/auth0_drupal": "^2.0.0",
>         "auth0/auth0-php": "0.6.*",
>         "adoy/oauth2": "dev-master",
>         "firebase/php-jwt" : "dev-master"

**Comment by glena** [comment]
and did you find those in the `vendor` directory?

for example `/vendor/adoy/oauth2`? (it should be in the vendor directory in the root path of your project)

**Comment by nlighteneddesign** [comment]
Sorry I wasn't clear.

I did verify they were in the vendor folder and I cleared cache.

I still receive the same error.

**Comment by josephdpurcell** [comment]
If you're using composer to manage your modules, you will have something like this in your drupal's composer.json:

```
    "extra": {
        "installer-paths": {
            "modules/contrib/{$name}": ["type:drupal-module"],
```

And all you need in your composer.json file is:

```
        "auth0/auth0_drupal": "^2.0.0",
```

Note: mine is actually set to "dev-drupal8" instead of "^2.0.0".

Then, running composer install will create modules/contrib/auth0_drupal" and you should have all the auth0 module dependencies in vendor:

```
vendor/auth0/auth0-php/
vendor/adoy/oauth2/
vendor/firebase/php-jwt/
```

Are you using composer to manage modules?

**Comment by nlighteneddesign** [comment]
I am not using composer to manage most modules, just this one. 

I just noticed that it installed in /modules rather than /modules/contrib.

After trying this it moved the module from /modules to /modules/contrib as expected. I still get the same error though when trying to log in.

I changed it from ^2.0.0 to dev-drupal8 and composer said there were no changes.

Here is my composer.json file 
```
{
    "name": "drupal/drupal",
    "description": "Drupal is an open source content management platform powering millions of websites and applications.",
    "type": "project",
    "license": "GPL-2.0+",
    "require": {
        "composer/installers": "^1.0.21",
        "wikimedia/composer-merge-plugin": "~1.3",
        "auth0/auth0_drupal": "^2.0.0",
        "auth0/auth0-php": "0.6.*",
        "adoy/oauth2": "dev-master",
        "firebase/php-jwt" : "dev-master"
    },
    "replace": {
        "drupal/core": "~8.1"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "preferred-install": "dist",
        "autoloader-suffix": "Drupal8"
    },
    "extra": {
        "installer-paths": {
            "modules/contrib/{$name}": [
                "type:drupal-module"
            ]
        },
        "_readme": [
            "By default Drupal loads the autoloader from ./vendor/autoload.php.",
            "To change the autoloader you can edit ./autoload.php."
        ],
        "merge-plugin": {
            "include": [
                "core/composer.json"
            ],
            "recurse": false,
            "replace": false,
            "merge-extra": false
        }
    },
    "autoload": {
        "psr-4": {
            "Drupal\\Core\\Composer\\": "core/lib/Drupal/Core/Composer"
        }
    },
    "scripts": {
        "pre-autoload-dump": "Drupal\\Core\\Composer\\Composer::preAutoloadDump",
        "post-autoload-dump": "Drupal\\Core\\Composer\\Composer::ensureHtaccess",
        "post-package-install": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup",
        "post-package-update": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup"
    }
}
```

**Comment by nlighteneddesign** [comment]
To give a bit more info:

1. I uninstalled and reinstalled the module
2. added client secret and site.
3. Go incognito to login get redirected to the sso page
4. Log in
5. Receive error

**Comment by josephdpurcell** [comment]
First thing, you want to decide how you want to manage downloading and installing modules. There are generally two recommended options (from the command line):

1. Use composer to download modules and their dependencies, then enable the module with drush or the admin
2. Use drush to download the module, use composer to install their dependencies, then enable the module with drush or the admin

Depending on which route you go, here are my thoughts:

# Using composer to download

If you're going to use composer, then first I would make one change which is that I see you have all 4 composer dependencies listed:

```
        "auth0/auth0_drupal": "^2.0.0",
        "auth0/auth0-php": "0.6.*",
        "adoy/oauth2": "dev-master",
        "firebase/php-jwt" : "dev-master"
```

You should only need `auth0/auth0_drupal` listed. It lists the other 3 as a dependency; composer will detect that and install them. So, remove all but the auth0/auth0_drupal from composer.

After doing that, if you still get the `Class 'Auth0SDK\Auth0' not found` error, make sure that the following file exists: `vendor/auth0/auth0-php/src/Auth0.php`. This is to confirm that composer properly installed the module's dependencies.

If it does exist and you still get the error, then... I'm a bit stumped but will have more ideas.

# Using drush to download

If you're not using composer to manage your modules, here is what I recommend:

1. Disable and remove the auth0 module, and also remove all of the auth0 related composer dependencies (just to start over from scratch)
2. Remove the "installer-paths" config you just put into your composer.json
3. Install the auth0 module using whatever method you are using (e.g. drush)
4. Run `composer require auth0/auth0_drupal:^2.0.0` to install all the composer dependencies you need

The end result should be that the `auth0_drupal` module is installed in the same directory as your other modules and the module's PHP dependencies are in `vendor` directory.

After that, if you're still having difficulties I am stumped but may have more ideas.

# Commentary on Composer

One quick thing to note about composer: you should never directly modify the composer.json file. Always use the CLI, which will manage the composer.lock file for you.

Typically you'll only need the following two commands:

* `composer require drupal/module` to install a dependency
* `composer install` to install all the dependencies identified in the `composer.lock` file

There are obviously more commands, but 90% of the time you just need those two.

**Comment by nlighteneddesign** [comment]
Thank you for taking the time to write this up.

I generally use drush to manage dependencies, I've used composer on projects with other clients that prefer that workflow with minimal issues.

My first attempt was to just install the module with the normal route, however since this isn't on d.o I just downloaded the module. I was missing the sdk and a couple other things so I attempted to use Composer.

The first thing I did with composer on this project was `composer require auth0/auth0_drupal:^2.0.0` and you can follow the rest of the chain from there.

I also tried manually downloading and running the require install command like you suggested, same error.

If I check vendor, I have adoy, auth0 and firebase all where they are expected.

**Comment by nlighteneddesign** [comment]
Ok I think I  just figured out the cause. For some reason it looks like when I commited everything the adoy library and the firebase library were git repos or submodules. The file structure looks like this: php-jwt → 3aa3d978973f [3aa3d978973f]

However when I look locally the files are all there, there is no .git or .gitignore preventing the folders from being added. when trying to run composer install on the server I get some errors cause I'm on php 5.6 locally and php 7 on the server if I confirm this I'll comment again.

**Comment by josephdpurcell** [comment]
Okay, great! So, you clearly have the files in the right places, the auth0_drupal module is in the modules directory with the other things and in vendor you have the dependencies.

It's clearly loading the auth0 module correctly, since it's the auth0 module that's throwing the error AND you can configure it.

It seems like the problem is surrounding Drupal's ability to load the vendor libraries, particularly the auth0-php library.

One possibility is a regression was introduced? This is a wild guess, but perhaps replace the corresponding lines in your composer.lock file with the following and then run composer install:

```
        {
            "name": "auth0/auth0-php",
            "version": "0.6.8",
            "source": {
                "type": "git",
                "url": "https://github.com/auth0/auth0-PHP.git",
                "reference": "98bebf6444086661d02877a44543fcb6c9636a70"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/auth0/auth0-PHP/zipball/98bebf6444086661d02877a44543fcb6c9636a70",
                "reference": "98bebf6444086661d02877a44543fcb6c9636a70",
                "shasum": ""
            },
            "require": {
                "adoy/oauth2": "dev-master",
                "ext-curl": "*",
                "ext-json": "*",
                "php": ">=5.3.0"
            },
            "type": "library",
            "autoload": {
                "classmap": [
                    "src"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Auth0",
                    "email": "support@auth0.com",
                    "homepage": "http://www.auth0.com/"
                }
            ],
            "description": "Auth0 PHP SDK.",
            "time": "2016-10-06 15:27:34"
        },
        {
            "name": "auth0/auth0_drupal",
            "version": "dev-drupal8",
            "source": {
                "type": "git",
                "url": "https://github.com/auth0/auth0-drupal.git",
                "reference": "cef32a01fc1d9b97f715c64934f6cf8cba1fd1dd"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/auth0/auth0-drupal/zipball/cef32a01fc1d9b97f715c64934f6cf8cba1fd1dd",
                "reference": "cef32a01fc1d9b97f715c64934f6cf8cba1fd1dd",
                "shasum": ""
            },
            "require": {
                "adoy/oauth2": "dev-master",
                "auth0/auth0-php": "0.6.*",
                "firebase/php-jwt": "dev-master"
            },
            "type": "drupal-module",
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "German Lena",
                    "email": "german@auth0.com"
                }
            ],
            "description": "Single Sign On for Enterprises + Social Login + User/Passwords. For all your Drupal instances. Powered by Auth0.",
            "time": "2016-10-13 12:23:54"
        },
```

**Comment by nlighteneddesign** [comment]
I got it, because of the difference in php versions I was missing the ext_mbstring extension I needed. I added that.

Next because composer is cloning those git repos I was essentially tying to commit a sub repo. The really confusing thing though is the file structure is right on my local machine. All of the files are there, and there are no .git or .gitignore files/folders.
On the server deleting the adoy and firebase folders and running composer install loads everything I need. This time there are .git and .gitignore folders. I will delete those and commit everything properly, thanks for your help guys, it's working now.

**Comment by josephdpurcell** [comment]
Great news! Glad to hear.

Keep in mind you are definitely not alone--while composer is, imo, the best feature of Drupal 8, it does introduce complexity and confusion with having dependencies not uniformly managed.

Happy to help if any composer or related issues come up.

**Comment by glena** [comment]
Awesome, thx @josephdpurcell for your help here :)

**Comment by nlighteneddesign** [comment]
Thanks guys, I think it's pretty clear I need to brush up on composer and this half and half approach is what is causing me some headaches.
