### ISSUE TITLE
Submit module to drupal.org

### ISSUE THREAD

**Issue by josephdpurcell** [auth0/auth0-drupal#65]
This module is great and provides a lot of value.

The ticket on Drupal.org to get this module accepted needs an Auth0 representative to submit back the status of the module in order for progress to continue: https://www.drupal.org/node/2298559

I think the two outstanding items for the Drupal 8 version are using dependency injection ([link](https://www.drupal.org/docs/8/api/services-and-dependency-injection/services-and-dependency-injection-in-drupal-8)) in place of Drupal::service. Here are current examples in code:

```
$ grep -Rn 'Drupal::'
src/Controller/AuthController.php:39:    $this->eventDispatcher = \Drupal::service('event_dispatcher');;
src/Controller/AuthController.php:47:    $config = \Drupal::service('config.factory')->get('auth0.settings');
src/Controller/AuthController.php:75:    $config = \Drupal::service('config.factory')->get('auth0.settings');
src/Controller/AuthController.php:107:    $config = \Drupal::service('config.factory')->get('auth0.settings');
src/Controller/AuthController.php:192:    $config = \Drupal::service('config.factory')->get('auth0.settings');
src/Controller/AuthController.php:294:    $config = \Drupal::service('config.factory')->get('auth0.settings');
src/Controller/AuthController.php:331:    $config = \Drupal::service('config.factory')->get('auth0.settings');
src/Controller/AuthController.php:459:    $config = \Drupal::service('config.factory')->get('auth0.settings');
src/Controller/AuthController.php:469:      $client = \Drupal::httpClient();
src/Form/BasicSettingsForm.php:29:    $config = \Drupal::service('config.factory')->get('auth0.settings');
src/Form/BasicSettingsForm.php:85:    $config = \Drupal::service('config.factory')->getEditable('auth0.settings');
src/Form/BasicAdvancedForm.php:29:    $config = \Drupal::service('config.factory')->get('auth0.settings');
src/Form/BasicAdvancedForm.php:152:    $config = \Drupal::service('config.factory')->getEditable('auth0.settings');
auth0.install:58:  $config = \Drupal::service('config.factory')->getEditable('auth0.settings');
```

The other is the BasicAdvancedForm::validateForm method can be removed since it does not have any code in it.

**Comment by arshad** [comment]
We'd like to see this happen too. Let us know if you need any help.

**Comment by dremy** [comment]
+1 can someone from Auth0 follow up? See https://www.drupal.org/node/2298559

**Comment by chronosinteractive** [comment]
we have a client considering Auth0 + Drupal right now. This module would go a long way toward closing the deal.

**Comment by rshepherd-dh** [comment]
+1

**Comment by rshepherd-dh** [comment]
Hey Guys, 

I've gone and created the module page on Drupal.org (https://www.drupal.org/project/auth0) and have pushed your tagged releases but change them to the Drupal format. I've also given the `auth0` user on drupal.org full access to the project.

I'm currently in the process of applying for permission to opt into security advisory coverage for the module so there are no releases as yet.

If you'd like anyone to have access/ownership please let me know.

**Comment by josephdpurcell** [comment]
Huzzah! I'll close this ticket since there is now a project page on drupal.org.
