### ISSUE TITLE
Drupal.org module

### ISSUE THREAD

**Issue by harmstyler** [auth0/auth0-drupal#86]
Is this package in sync with the [drupal.org](https://www.drupal.org/project/auth0) module? It doesn't appear to be the case. In the case that the two repos have diverged, which one is recommended?

**Comment by joshcanhelp** [comment]
@harmstyler - Looking into this now. We've got a new version of the Auth0 PHP SDK being added and tested now and we'll get the module and this repo in sync as part of that process.

**Comment by joshcanhelp** [comment]
For anyone else wondering on this ... we're working with @rob3000 to get these two on the same page. Our internal maintainers are using `master` here for Drupal 8 but it looks like the Drupal.org module has been more actively maintained. We're working out a plan right now to get these synced up in both places, get version numbers the same, and make sure it stays that way going forward.

**Comment by truls1502** [comment]
Any updates on it?

**Comment by joshcanhelp** [comment]
The PR is just above your comment. This is going slower than I hoped due to a big release in one of our other libraries. I'll have some time later this week to make progress.

**Comment by margyly** [comment]
What's the status of this? I added the Auth0 module to Drupal 8 using composer. Does that get me the right version?

Thanks in advance!

**Comment by joshcanhelp** [comment]
@margyly - Composer pulls from this repo and that is probably the best version to use right now. This particular library is community-supported at the moment (meaning: not official Auth0 software) but I'm working closely with the maintainer to get it up-to-date and on Drupal.org.

**Comment by truls1502** [comment]
Let me or us know if you need us to test the up-to-date module or dev module. 😊 I would be happy if you can get the module on 7.x version too. 😉

**Comment by joshcanhelp** [comment]
@truls1502 - Really appreciate that, thank you! We're mainly concentrating on D8 but will look into getting this pushed to D7 as well.

**Comment by truls1502** [comment]
@joshcanhelp - you are welcome! Let me know if you need an extra hand, I will try to give a patch if I find something not right on https://www.drupal.org/project/issues/auth0

**Comment by margyly** [comment]
@joshcanhelp When I install the module and configure it, attempting to log in gives me this message: WE COULD NOT REACH THE SERVER. PLEASE CHECK YOUR CONNECTION AND TRY AGAIN.

And I'm seeing this network error: Failed to load https://uua.auth0.com/usernamepassword/login: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://3910-auth0-ye4wami-2gsgzx7spxgoy.us.platform.sh' is therefore not allowed access.

Any ideas how to solve this? Thanks in advance!

**Comment by joshcanhelp** [comment]
@margyly - That sounds like a configuration issue in your dashboard. Make sure you have the correct URLin the "Allowed" fields in your Application settings, specifically "Allowed Origins (CORS)" (sounds like that should at least have `https://3910-auth0-ye4wami-2gsgzx7spxgoy.us.platform.sh/`)

**Comment by joshcanhelp** [comment]
Try adding `https://3910-auth0-ye4wami-2gsgzx7spxgoy.us.platform.sh` to the Allowed Origins field. This issue often comes up during configuration so I'm pretty sure it's not a module issue but it could be. 

If you're still having a problem here and you suspect it's a Drupal module problem, can you open a separate issue here? I'd like to keep this thread specific to the OP's topic. Thank you!

**Comment by margyly** [comment]
My apologies -- I didn't mean to hijack this issue. New issue is at https://github.com/auth0/auth0-drupal/issues/108.

**Comment by hawkeyetwolf** [comment]
Thanks so much for your work on this, @rob3000! The `master` branch of this repo works, while the 2.x branch in the drupal.org repo does not. Let's get this up there! :) I'm happy to perform the initial push and figure out an automatic synchronization if you'd like. I would just need write access to the project on d.o.

**Comment by rob3000** [comment]
Hey @hawkeyetwolf Sorry for the late reply there is one last PR that i'd like to get in before syncing them across and thats making sure the module uses dependency injection so we dont need to use \Drupal:: everywhere. I've created a PR here https://github.com/auth0/auth0-drupal/pull/109 and once this gets merged happy to then get them all synced up :)

**Comment by joshcanhelp** [comment]
Quick update here ... with lots of help from @rob3000, we've got the `master` branch of this repo in good shape and working for both new and legacy tenants. I'm going to be doing a bit more testing in the next day or two, then we'll push these changes to the Drupal.org module. Should not be any breaking changes and everything is working well so far so you're welcome to give `master` here a test. 

Thank you!

**Comment by joshcanhelp** [comment]
Last update here ... I'm going to publish a `2.1` release here and sync up the Drupal repo tomorrow. When that's complete, I'll close this down and we'll be all synced up!

**Comment by truls1502** [comment]
I can't see 2.1 on Drupal.org yet :)

**Comment by joshcanhelp** [comment]
[Done (here)](https://github.com/auth0/auth0-drupal/releases/tag/8.x-2.1) and [done (DO)](https://www.drupal.org/project/auth0/releases/8.x-2.1)! Please open a new issue here if you have any problems with the latest. @rob3000 and I will be triaging the issues and bugs on DO in the near future. 

Thanks everyone for your help and patience here!
