### ISSUE TITLE
Why so many uncommented PRs? 

### ISSUE THREAD

**Issue by justinlevi** [auth0/auth0-drupal#92]
I'm a bit concerned about the number of PRs that have been sitting out there with no comments. Is this module still being actively maintained/developed?

**Comment by joshcanhelp** [comment]
Hi @justinlevi ... this repo has fallen a bit behind, as you can see, but we're in the process of getting it up-to-date. The module on DO was being community maintained and fell out of sync with this repo. We have some security updates [being tested](pull/88) now, then we'll work with the main maintainer on DO to get that repo synced with this one. 

I'll answer your other two issues as soon as I can.
