### ISSUE TITLE
Duplicate EmailNotVerifiedException caught in AuthController::processUserLogin

### ISSUE THREAD

**Issue by joshcanhelp** [auth0/auth0-drupal#95]
`$this->validateUserEmail($userInfo)` catches missing email or missing verification, then `$user = $this->signupUser($userInfo)` later on catches missing verification. We should not catch the same error twice. 

Reported by @lbalmaceda [here](https://github.com/auth0/auth0-drupal/pull/88#discussion_r179248399)

**Comment by mptap** [comment]
@joshcanhelp Have opened #117  - wrapped the if else block with try and moved the exception outside. Let me know if you have a different approach in mind. Happy to contribute for Hacktoberfest 2018!
