### ISSUE TITLE
Import picture on sign up

### ISSUE THREAD

**Issue by timrabbetts** [auth0/auth0-drupal#98]
I would like to pull the avatar from gmail on signup and store it in drupal?

**Comment by joshcanhelp** [comment]
This is a bit out of scope for the SDK or the Drupal module. Depending on how you setup the social connection, this data could be grabbed from the [management API](https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id
) or a [custom claim](https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims) on the user profile.
