### ISSUE TITLE
Ability to assign role to users signed up with auth0 within drupal.

### ISSUE THREAD

**Issue by timrabbetts** [auth0/auth0-drupal#99]
When a user signs up or logs in with auth0 to drupal site, they have no roles be nice to auto assign in some way a role, or have a rule maybe if auth0 sign up then do x.??

**Comment by timrabbetts** [comment]
Could I get some advice on how to modify this module so we can have option of assigning a user role to auth0 users please?

**Comment by joshcanhelp** [comment]
@timrabbetts - Are you looking to assign a specific role to new users created with Auth0 or do you want to assign roles to users based on data that's stored in Auth0? The latter is a discussion we're having internally for all the CMSes we support, hence the `enhancement` tag. The former is something you should handle in your own module, probably after the user creation process (look for the stored Auth0 ID).

**Comment by timrabbetts** [comment]
Managed to patch it and got profile pic etc working.

**Comment by timrabbetts** [comment]
Can close if you want.

**Comment by lalit774** [comment]
> Managed

can you please share the patch for auth0?
